# Generated by Django 4.2.25 on 2025-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompalintAndReplay',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=100)),
                ('replay', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'compalint_and_replay',
                'managed': False,
            },
        ),
    ]
