# Generated by Django 4.2.25 on 2025-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('adr_id', models.IntegerField()),
                ('sreg_id', models.IntegerField()),
                ('payment', models.CharField(max_length=45)),
                ('reg_id', models.IntegerField()),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
