# Generated by Django 4.2.25 on 2025-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAndRating',
            fields=[
                ('feed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feed_back', models.CharField(max_length=45)),
                ('rating', models.IntegerField()),
                ('reg_id', models.IntegerField()),
            ],
            options={
                'db_table': 'feedback_and_rating',
                'managed': False,
            },
        ),
    ]
