# Generated by Django 3.2.25 on 2026-01-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'delivery_status',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
