# Generated by Django 4.2.25 on 2025-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'catagory',
                'managed': False,
            },
        ),
    ]
