# Generated by Django 4.2.25 on 2025-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
                ('image_of_product', models.CharField(max_length=500)),
                ('stock_quantity', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
            ],
            options={
                'db_table': 'add_product',
                'managed': False,
            },
        ),
    ]
